name: Lint

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Run lint
        run: yarn lint | tee lint_result.txt

      - name: Check lint result
        run: |
          if ((Test-Path lint_result.txt) -and ((Get-Content lint_result.txt) -match 'error|warning')) {
            Get-Content lint_result.txt | Select-String -Pattern 'error|warning'
            exit 1
          }
